{{- if not .Values.credentials.secretName -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp.fullname" . }}-credentials
  labels:
    {{- include "mcp.labels" . | nindent 4 }}
  annotations:
    {{- include "mcp.annotations" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.credentials.platformUser }}
  ITENTIAL_MCP_PLATFORM_USER: {{ .Values.credentials.platformUser | quote }}
  {{- end }}
  {{- if .Values.credentials.platformPassword }}
  ITENTIAL_MCP_PLATFORM_PASSWORD: {{ .Values.credentials.platformPassword | quote }}
  {{- end }}
  {{- if .Values.credentials.platformClientId }}
  ITENTIAL_MCP_PLATFORM_CLIENT_ID: {{ .Values.credentials.platformClientId | quote }}
  {{- end }}
  {{- if .Values.credentials.platformClientSecret }}
  ITENTIAL_MCP_PLATFORM_CLIENT_SECRET: {{ .Values.credentials.platformClientSecret | quote }}
  {{- end }}
{{- end }}
